[package]
name = "jni-loader"
edition = "2021"
version = "0.1.0"
authors = ["Charley Wright"]
description = "Load Android shared libraries on Linux"
license = "MIT"
repository = "https://github.com/charleywright/jni-on-linux"
exclude = ["test"]

[dependencies]
auxv = "0.3.3"
thiserror = "1.0.56"
